### ISSUE TITLE
IE Support?

### ISSUE THREAD

**Issue by grahamb** [gaearon/react-dnd#106]
What's the state of IE support for react-dnd? I've implemented a sortable component, and it works on IE 10 & 11 (although the cursor changes to circle-with-a-line while a card is being dragged), but doesn't on IE 9. Dragging causes text to be selected, and I can occaisionally cause a drag to actually initiate but only about 0.5 times out of ten, and when it does there's no visible drag happening - just a bilp and a re-order.

**Comment by gaearon** [comment]
I test with IE10+, versions before that are unlikely to be supported unless somebody else fixes them.

There's one issue with IE10+ I'm aware of: custom element `dragPreview` don't work. This is because `setDragImage` is just not supported by IE.

This especially hurts [custom drag layers](http://gaearon.github.io/react-dnd/#/drag-around-custom) because the “real” DOM element is still visible on IE, whereas in other browsers we use an empty image.

One way to “fix” that would be to treat `dragPreview: null` as explicit way to set empty drag preview (#88),  and once we have that API, hide original element just before it gets dragged in IE when `dragPreview` is `null`. This may at least prevent the screenshotting.

This won't be a big issue in 1.0 where we plan to have swappable drag and drop implementations. For example, if you care about IE a lot, you'll be able to switch to mousemove-based implementation that doesn't have these problems. But for now I'm open to considering various workarounds like the one I suggested above for `dragPreview`.

Hope this helps!

**Comment by gaearon** [comment]
As for the cursor problem, can you please file an additional issue specifically for that? I think I fixed this once but there may have been a regression.

**Comment by grahamb** [comment]
Thanks - I've opened #107 about the cursor. Looking forward to 1.0!

**Comment by nelix** [comment]
Another issue with IE support and http://gaearon.github.io/react-dnd/#/drag-around-custom is that IE9 (and even 10?) don't support pointer-events-none? We can fix that using document.msElementsFromPoint?

**Comment by gaearon** [comment]
I think such effort would be wasted without a third party backing this and making sure it's properly implemented (and then maintained).

**Comment by nelix** [comment]
The only way to make the DragLayer work on IE10 is msElementsFromPoint or rapidly showing and hiding the overlay and using elementFromPoint. Prolly something for later when other backends become available... Perhaps a simple out of the box DragLayer component.
I agree its best not to do anything now, but in the future I have some code in production that handles this on IE9 and IE10 that we could look at.
