### ISSUE TITLE
isDragging

### ISSUE THREAD

**Issue by LukasUrban** [gaearon/react-dnd#108]
Hi, I'm having problem with ```isDragging``` - it stays on original position instead of moving with dragged element (red border). This probably is not a bug, just me not knowing how this works.

I'm updating data via flux, doing nothing with ```isDragging```. 

http://fluid.cz/projects/react-dnd/

http://fluid.cz/projects/react-dnd/code.zip

Thanks for help

**Comment by gaearon** [comment]
`isDragging` only reflects the state of dragging. The item won't move “by itself” because we're not touching the DOM in React DnD—we're letting you do it.

You have two options:

* Let the browser draw drag preview (happens by default) and hide the “real” component when `isDragging` is `true` by either returning `null` from `render` or using `opacity: 0`. [Sortable example](http://gaearon.github.io/react-dnd/#/sortable-simple) covers this technique.
* Give the browser an empty image as drag preview (note that this currently won't work in IE). Use a custom drag layer to draw your own component as it moves across the screen. This way you can have any customization you want. [Drag around custom](http://gaearon.github.io/react-dnd/#/drag-around-custom) example covers this technique.

Hope it helps!

**Comment by LukasUrban** [comment]
Problem is not moving the component, or the dragPreview. ```isDragging``` prop is attached to whatever component matching original index of component which being dragged.

**Comment by gaearon** [comment]
Oh, I see your point now. The problem in your example is fixed by giving your items a `key`. There's a warning in console about that. If you give them `key`s, React will move the original component, so `isDragging` will be relevant.

It's not perfect we can't handle the situation gracefully without keys. This will be a good stress case for whatever API we implement in #64 but we don't support this yet.

**Comment by LukasUrban** [comment]
I added unique key prop to each child, but it still acts the same. I uploaded current version of example, just refresh it http://fluid.cz/projects/react-dnd/

**Comment by gaearon** [comment]
No problem!

**Comment by optimatex** [comment]
this solution solved my problem too! thank u
