### ISSUE TITLE
Difficulties with nested dragSource

### ISSUE THREAD

**Issue by jbelcher** [gaearon/react-dnd#122]
I have a NativeFile dropType on my main app wrapper to accept files from the desktop. Inside of that wrapper, I'm having trouble getting other react-dnd dragSources working. 

See: http://jsbin.com/wivujopoge/4/edit?js,console,output

You can drag and drop a file into the app fine, but the child dragSource is not draggable. It looks like the mixin is adding `draggable="true"` to the nested dragSource correctly.

Swap out the top level component for `<AppWithoutFileDrop />` and you'll see the child is now draggable.

**Comment by gaearon** [comment]
That won't work because you're creating a new class each time `makeDropThing` runs. Because class is different, React bails out of diffing and unmounts the original component.

In the next version, it will be possible to persist drag source state even across unmounting/remounting components, but you don't need this. All you need it to extract class creation and create it once:

http://jsbin.com/wibukiyave/2/edit

You also *only* need that factory function if you plan to have similar components with different types. If you don't need that, just create a single drag source component that uses a constant type:

http://jsbin.com/nelupawasa/2/edit

**Comment by jbelcher** [comment]
@gaearon I do have similar components with different types in our case, but I grok what's happening now. Thanks for the explanation!

**Comment by gaearon** [comment]
By the way 0.10 won't need those wrappers, you'll be able to use `props` for that. Stay tuned for updates!

**Comment by gaearon** [comment]
With the new API, you can pass `props => props.whatever` as `type` and have the dynamic type registration.

**Comment by jbelcher** [comment]
Thanks Dan—going to look into this soon.
