### ISSUE TITLE
Access the item being dragged from the dropTarget render method ?

### ISSUE THREAD

**Issue by jerefrer** [gaearon/react-dnd#132]
Hi there, and thanks for the awesome library :)

I'm wondering if it's possible to know the item being dragged from a `dropTarget`. As far as I understand I can check if *something* is dragged or if *something* is hovering the `dropTarget`, but not what this *something* actually is.

My problem is that I'd like to access some properties of the item being dragged from the `dropTargets` so I can change the background color of those `dropTargets` depending of the value of those properties.

What I don't want to do is ever *prevent* the user from dropping in the `dropTarget`, so the `canDrop` function wouldn't help.

Let me explain a bit further what I intend to do:

In my app I can drop a `User` inside a `DayCell`. If the `User` stated that he is available for that particular day, then set the `DayCell` background to green. If he stated that he is not available, set it to red. If he hasn't stated anything, then set it to gray so we can still see it's a valid `dropTarget`. We never prevent the admin from dropping a `User` in a `DayCell`, we just suggest that it would be a good or a bad idea to do so.

What do you think ? Is it already possible ? If not how about adding the item being dragged to the `dropState` object so we can access it from the `dropTarget` ?

**Comment by gaearon** [comment]
Indeed, right now `getDropState()` only returns `isHovering`/`isDragging` with no distinction regarding item properties. You still get [`enter`, `over` and `leave`](https://github.com/gaearon/react-dnd/blob/master/docs/API.md#entercomponent-reactcomponent-item-object) in `dropTarget` with `item` as second parameter, so instead of using `getDragState` for hovering you can maintain some binary state in your component, and call `setState` from `enter` and `leave` under certain conditions.

This whole issue will be moot with a next major API change/rewrite (#109) which is in active development now. The next API will allow to express what you want much more cleanly and explicitly.

**Comment by jerefrer** [comment]
Ok that's what I feared, having to keep track of the state myself ^^
I'll wait for the new API then, it will motivate me to update !

Thanks for the quick answer, and have fun refactoring :)

**Comment by gaearon** [comment]
This is now possible in 1.0. Your [collecting function](http://gaearon.github.io/react-dnd/docs-drop-target.html#the-collecting-function) may take `monitor.getItem()`, and your component will receive it in props.
