### ISSUE TITLE
Sortable always rejects dragged item.

### ISSUE THREAD

**Issue by asivokon** [gaearon/react-dnd#138]
The easiest way to see this issue visually, is to open sortable-simple example in Firefox. It looks like this:

![sortable-animation](https://cloud.githubusercontent.com/assets/2910707/7207189/3ca7a696-e540-11e4-94d5-20df0e81fa22.gif)

Note the revert animation: element moves back to its initial position, which is quite annoying.

Deeper problem is that, it seems, there's no way to make sortable distinguish success drops vs. failed ones (e.g. when moved outside the list area).

I think it happens because we modify model as we drag item around, so we always end dropping item on itself, which causes drop rejection. Any suggestions on how to overcome this would be very helpful!

Thanks!

**Comment by gaearon** [comment]
>Note the revert animation: element moves back to its initial position, which is quite annoying.

There is actually special code to cancel the animation if the source node position has changed, but it is currently only enabled for Webkit. I'll take a look whether it's easy to apply the same fix for FF.

>Deeper problem is that, it seems, there's no way to make sortable distinguish success drops vs. failed ones (e.g. when moved outside the list area).

You're right. The reason it happens is because, currently, [we don't consider dropping item on itself a successful drop](https://github.com/gaearon/react-dnd/issues/95#issue-59107588). This is a technical limitation and **will be removed in the next version**. In fact, you shouldn't see this behavior in Firefox in `dnd-core` branch (this is the next version).

The ETA for next version release is first week of May.

**Comment by gaearon** [comment]
I'm closing the issue. It is fixed in `v1.0.0-alpha` which is available on NPM.
The final 1.0 release is coming in a week or so.
