### ISSUE TITLE
Is there a way to constrain sortable list into it's axis

### ISSUE THREAD

**Issue by mech** [gaearon/react-dnd#147]
When implementing sortable list, it is often nice to constraint the axis to either vertically or horizontally only, I am wondering if react-dnd has such options?

Sort of like what jQuery-UI does:

```js
$( ".selector" ).sortable({
  axis: "x"
});
```

**Comment by gaearon** [comment]
By default, we are using HTML5 drag and drop API. It is impossible to customize the drag preview movement in it: wherever the mouse goes, the drag preview will move.

However, with React DnD, you can supply *an empty image* as a drag preview for the browser. If you do so, the browser won't draw anything, and it is up to you to implement constrained dragging by axis. You can use a [custom drag layer](http://gaearon.github.io/react-dnd/#/drag-around-custom) to do this.

So, it's not a built-in feature (it would be impossible to do this built-in without manipulating the DOM, which is against these library's goals), but it's doable with custom drag layers. Note that a custom drag layer won't work in IE 10 because it has no support for `pointer-events: none`.

**Comment by mech** [comment]
Appreciate the info.

**Comment by badasukerubin** [comment]
I wrote a tip for this here: https://toluwaniadewale.com/blog/constrain-react-dnd-to-the-horizontal-axis
