### ISSUE TITLE
Sortable example performance dropped when passing JavaScript object instead of primitive

### ISSUE THREAD

**Issue by mech** [gaearon/react-dnd#229]
Hi, I am not sure this is a React issues, philosophy issues or DnD issues.

Let's say I have 100 items that is to be sortable. Using the Simple Sortable card example, if I pass in the props as the real `card` object, dragging performance is very laggy.

```js
// In Container.js render() method
render() {
  {cards.map(card => {
    return (
      <Card key={card.id}
        id={card.id}
        card={card} // Hey, I am passing the whole JavaScript object instead of primitive string
        moveCard={this.moveCard} />
    );
  })}
}
```

My question is, is this a terrible idea? to pass in the props the whole JavaScript object. Or is it that React component's props must be primitive and cannot be object when it comes to array iteration of a huge list?

**Comment by gaearon** [comment]
React DnD [tries to help you](https://github.com/gaearon/react-dnd/blob/163694019d2a386f09eb039233fb58cd0e546241/src/decorateHandler.js#L43-L46) to have a good perf by default. Unfortunately it can't make guesses about how your data is structured, so as soon as you pass an object, it falls back to a naïve (and less performant) default because it doesn't know how to compare your objects. It doesn't know whether you mutate them deep inside or not. If you're not familiar with `shouldComponentUpdate` optimizations, [check out this article](https://facebook.github.io/react/docs/advanced-performance.html).

You can override its naïve logic by passing a custom `arePropsEqual` function inside the `options` argument. This way you can tell React DnD how to compare your custom objects and in which case they are considered equal.

From [`DragSource` docs](http://gaearon.github.io/react-dnd/docs-drag-source.html):

>`options`: Optional. A plain object. If some of the props to your component are not scalar (that is, are not primitive values or functions), specifying a custom `arePropsEqual(props, otherProps)` function inside the options object can improve the performance. Unless you have performance problems, don't worry about it.

Example:

```js
// Let's say you promise to never mutate card object inside
// and you guarantee that if it changes, the whole reference changes.
// Then we can use more aggressive shallowEqual as default comparison:

import shallowEqual from 'react-pure-render/shallowEqual';

let options = {  arePropsEqual: shallowEqual };
export default DragSource(type, spec, collect, options)(MyComponent);
```

You can also specify a custom function:

```js
function arePropsEqual(nextProps, props) {
  return nextProps.id === props.id &&
          nextProps.moveCard === props.moveCard &&
          nextProps.card === props.card; // or some more sophisticated comparison
}

let options = {  arePropsEqual };
export default DragSource(type, spec, collect, options)(MyComponent);
```

but be careful to avoid false negatives. Generally relying on something like `shallowEqual` and never mutating existing data is enough to get good performance.

**Comment by mech** [comment]
Thanks for the explanation!! I need and go and learn more on my data structure and `shouldComponentUpdate` first.
