### ISSUE TITLE
Cursor appearance across different browsers

### ISSUE THREAD

**Issue by sbai** [gaearon/react-dnd#270]
I'm having some trouble getting the mouse cursor to look consistent in different browsers. On the [drop effects example](http://gaearon.github.io/react-dnd/examples-customize-drop-effects.html), Chrome and Safari on OS X change the cursor from the move cursor to the arrow when dragging an item, unless it's over the target. In Firefox, it stays as the move cursor. IE 11 and Chrome on Windows switch to a slashed circle / not allowed cursor unless the item is over the target. And in IE, the two items both have the copy cursor when hovering over the target, while Chrome and Firefox respect the fact that they have different drop effects specified.

It's not clear to me whether these differences in browser behavior are something that can be addressed in react-dnd. I was not able to override the cursors via CSS. Is there a way of getting around this issue when using the HTML5 drag and drop backend?

**Comment by ayozebarrera** [comment]
I'm having the same issue. Some help please

**Comment by ayozebarrera** [comment]
any advance on this guys?

**Comment by joshmatz** [comment]
I was also running into this and tried to start a conversation on Gitter: https://gitter.im/gaearon/react-dnd?at=55d60a7b0d29ce8f44b72759

I believe it's due to the HTML5 backend being used in ReactDnD by default. Because of the HTML5 tie-in, the cursors are controlled by the browsers through the HTML5 drag and drop API. The browsers have a limited subset of options (move, copy, not-allowed) available when the DnD API is active different behavior across browsers allows some to set the cursor via CSS but others ignore the cursor CSS.

Unfortunately, I think the way to get around this is to create an alternative non-HTML5 backend to not use the HTML5 DnD API when you want more control.

**Comment by sbai** [comment]
@joshmatz That's what I was afraid of. It seems to me that the HTML5 dnd API simply behaves too inconsistently, and is too poorly designed, to use as the default backend in production. My understanding is that react-dnd does certain things to smooth over the differences under the hood, but it may be better to use traditional mouse events for the default backend in the future, since that gives CSS control over the cursor. I guess we'll have to build our own backend until something gets rolled into react-dnd itself.

**Comment by gaearon** [comment]
These are just browser differences. Indeed, if you want to fully control the cursor, you need a custom (mouse) backend.

**Comment by navalarya** [comment]
I supposed we can have a configurable cursor instead of need for custom backend. This kind of unification is what we are looking for in a library.

**Comment by FullstackJack** [comment]
Anyone care to share their custom ReactDnD backends?

**Comment by genechuah** [comment]
Has someone found the solution?
