### ISSUE TITLE
Error when unmounting dnd-source

### ISSUE THREAD

**Issue by mistadikay** [gaearon/react-dnd#277]
After updating to `v1.1.6` I noticed that when dnd-source is unmounting I have the following error:
`Uncaught Error: Invariant Violation: Expected to find a valid source.`

It's probably related to upgrading `dnd-core` to `1.2.0` since on `1.1.0` everything is working fine. Also this bug appears on `react-dnd@1.1.5` as well because of [the way you manage your dependencies](https://github.com/gaearon/react-dnd/issues/276)

Error stack trace is below:
![screen shot](https://cloud.githubusercontent.com/assets/742056/9869367/778c9cce-5bad-11e5-89ba-8f9adeba5630.png)

**Comment by vkbansal** [comment]
@mistadikay I've updated to `v1.1.6` and tested, but was not able to reproduce the error.

**Comment by mistadikay** [comment]
@vkbansal I'll try to localize the source of the problem and maybe provide an example on which it can be reproduced

**Comment by mech** [comment]
Yes, I can confirm I got the same error also in `browser.js`. It happen when dragging and then quickly route to another page which I guess is the time when it is doing un-mounting.

**Comment by gaearon** [comment]
>It's probably related to upgrading dnd-core to 1.2.0 since on 1.1.0 everything is working fine. Also this bug appears on react-dnd@1.1.5 as well because of the way you manage your dependencies

I manage dependencies according to semver. The fact that DnD Core was rewritten is an implementation detail. It deserves a minor version bump there, but for React DnD the contract has not changed at all, so I see no reason jumping versions. If there are bugs, please add failing testcases in DnD Core and we'll fix them.

**Comment by vkbansal** [comment]
@gaearon How do I force `react-dnd` to use `dnd-core@1.1.0`? (As a temp workaround for this bug)
I need to deploy my code to production ASAP. Please Help.

**Comment by gaearon** [comment]
You can use [`npm shrinkwrap`](https://docs.npmjs.com/cli/shrinkwrap) to lock dependencies.

**Comment by gaearon** [comment]
Can you provide a reproducing case? This must be an easy fix but I can't get any of the examples to trigger the error.

**Comment by gaearon** [comment]
Okay, so here's what I found. The problem was due to a bug in `react-dnd` itself, but changes to `dnd-core` caused it to surface. I did the following:

* Released `dnd-core@1.2.1` with a [fix](https://github.com/gaearon/dnd-core/commit/e57f00c23b74106fbfca1f4ee0b24d108ea9cb3a) attempting to make the `react-dnd` bug harmless again, so even `react-dnd@1.1.5` should work fine in combination with it
* Deprecated `dnd-core@1.2.0` so people don't get it with old `react-dnd` versions by default
* Released `react-dnd@1.1.7` which, in addition to depending on `dnd-core@1.2.1`, contains [the actual bug fix](https://github.com/gaearon/react-dnd/pull/278) for the underlying bug

Please let me know if you find other issues, or if this bug resurfaces.

**Comment by gaearon** [comment]
Also, I'm sorry I messed up your production stuff. If there are more issues, I'll happily release the old version on top of the new one.

**Comment by mistadikay** [comment]
I can confirm that the bug is fixed. Thanks Dan for the quick fix!

**Comment by vkbansal** [comment]
@gaearon The problem has been fixed apparently.  Thanks a ton!

Will let you know if I face any more issues.

**Comment by gaearon** [comment]
Thank you for reporting!
