### ISSUE TITLE
Sortable example doesn't work in IE

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-dnd#28]
I fixed a few IE crashes in 0.6.2 but for some reason [sortable example](http://gaearon.github.io/react-dnd/#/sortable-simple) does not appear to be working in IE11 (items are dragged but not moved). It's either an issue with the example (lacking or differently named `MouseEvent` properties?), or with some part of library—worth investigating.

**Comment by ojame** [comment]
Looks like both `.enter` and `.leave` work - but `.over` doesn't. Putting `onDragOver={event.preventDefailt()}` on the card fails to turn the cards into drop targets. When you drag a card over another card, it shows the `no-drop` cursor.

Changing the cards from `divs` to `inputs` fixes the issue and has the desired effect. This is _only_ because inputs are accepted drop targets [by default](https://msdn.microsoft.com/en-us/library/ie/ms536929%28v=vs.85%29.aspx).

**Comment by itrelease** [comment]
https://github.com/gaearon/react-dnd/pull/74

**Comment by itrelease** [comment]
While fixing this bug I found statement that `e.preventDefault()` should be called also in `start` phase, it's also prevent text selecting in `Mouse.js` backend. So maybe pull out this call from condition and invoke it always?

**Comment by gaearon** [comment]
Let's look at that after I merge #72 (probably Monday)

**Comment by gaearon** [comment]
Fixed in master.
