### ISSUE TITLE
Sortable list in a ruby on rails app using turbolinks

### ISSUE THREAD

**Issue by m-baaziz** [gaearon/react-dnd#281]
Hi,
I tried to reproduce the simple sortable list in a ruby on rails app. This app is using Turbolinks (https://github.com/rails/turbolinks). Turbolinks prevents the browser from recompiling the JavaScript and CSS between each page change. Only the body and title is changed, making the app a little bit faster.

Here is the problem:
When i load the page for the first time, my list is rendered correctly and react dnd works fine. However, if i visit the page for a second time,  the react components of my list are rendered, but the dnd part dont work anymore: when i try to drag and drop an item, the beginDrag function is executed, but no hover is detected. After that, when i try to drag for the second time, i get this error message : "Invariant Violation: Cannot call beginDrag while dragging". If i don't refresh the page, all the other attempts lead to the same error message.

**Comment by gaearon** [comment]
>Turbolinks prevents the browser from recompiling the JavaScript and CSS between each page change. 

Browsers don't recompile JS and CSS on page change. I'm afraid this is not a correct description of what Turbolinks do. In any case, using React with Turbolinks seems very error-prone to me because both try to manage the DOM. React will freak out if something else changes the DOM.

It's hard to say something else without seeing a reproducing case, but we are unlikely to support this scenario anyway because it's contrary to how React works.

**Comment by rpechayr** [comment]
Hi @gaearon,

*disclaimer: I am @m-baaziz manager*

I would definitely agree with you to say that turbolinks and react do not play nicely with each other. However in this case, rendering the list in react works just great. This starts going wrong when we try to dnd our component for the second time. 

It is perfectly ok for you not support this scenario, however would you have any idea of the cause of the problem ? Here is a detailed description of the issue : 

1. Load the home page using `cmd-R` (the home page does not contain the sortable link)
2. Navigate to the list page: `react`  :heavy_check_mark:  and `react-dnd` :heavy_check_mark:. This is the first time the whole `bundle.js` file coming from browserify is loaded. 
3. Leave the page and go somewhere else : turbolinks does replace the whole body upon each request *without recompiling `css` and `js`*. We are talking here about the standard js and css from our Rails app. The react part has been removed from the dom since we are no longer in the list page. 
4. Come back to the list page without pressing `cmd-R`: The list is correctly displayed, so `react` :heavy_check_mark:, but `react-dnd` :heavy_multiplication_x:. This is the second time bundle.js is loaded. 

The only assumption I see here is that `bundle.js` has a global state somewhere, and it is probably coming from `react-dnd`. Do you think it is what is happening ? 

I anyone uses a pjax for example, and then tries to render a react component in this page, he could have the same problem.

**Comment by rpechayr** [comment]
We've worked around this issue by disabling turbolinks on this page, which is not a big deal

**Comment by gaearon** [comment]
Can I ask you to prepare a repro case without Turbolinks?
e.g. simulate what it does to the page.

**Comment by rpechayr** [comment]
Will do. This is a good idea. In particular it might help find possible annoying bugs in react-dnd. By the way, this library really rocks
