### ISSUE TITLE
Documentation and examples

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-dnd#3]
I'll add a usage overview in README but it would be nice to make a Github page with a sample app.
If anyone's interested, let me know.

**Comment by jean-Phil** [comment]
This isn't really an issue, but does concern the examples and might be useful to other novices like myself.  
I'd like to deconstruct your examples in order to understand what's going on (quite a bit is over my head, still).  However, I tried to bundle my changes using your webpack.config, but I get a compiling error I can't debug: _The line requires 'is-array', which seems to be present in the module dependencies..._


<pre>
ERROR in (webpack)/~/node-libs-browser/~/buffer/index.js
Module not found: Error: Cannot resolve module 'jsx' in /usr/local/lib/node_modules/webpack/node_modules/node-libs-browser/node_modules/buffer
 @ (webpack)/~/node-libs-browser/~/buffer/index.js 10:14-33
</pre>

I also tried to bundle using browserify, but it throws an exception when reaching one of the example partials where you define variables in a way I've never encountered before. *Would you be so kind and explain to me the declaration of variables _PropTypes_ and _DragDropMixin_?* I tried to break this into defining them as empty objects, and then assigning them their given values, but to no avail.

<pre>
var React = require('react'),
    ItemTypes = require('./ItemTypes'),
    { PropTypes } = React,
    { DragDropMixin } = require('react-dnd');
</pre>

I don't know much of proper github etiquette, and hope this is a proper way to proceed. I thank you in advance for your help.

JPL

**Comment by gaearon** [comment]
>Module not found: Error: Cannot resolve module 'jsx' in /usr/local/lib/node_modules/webpack/node_modules/node-libs-browser/node_modules/buffer

Do you have `jsx-loader` in `package.json` (and thus `node_modules`)? Looks like it's missing.  
This is what Webpack uses to convert JSX to JS.

>Would you be so kind and explain to me the declaration of variables PropTypes and DragDropMixin?

Sure, it's just [ES6 destructuring syntax](https://leanpub.com/understandinges6/read/#leanpub-auto-destructuring-assignment). You don't have to use it, basically this snippet is the same as:

```js
var React = require('react'),
    ItemTypes = require('./ItemTypes'),
    PropTypes = React.PropTypes,
    DragDropMixin = require('react-dnd').DragDropMixin;
```

It's a syntax sugar from ES6 (next version of JS). Although most browsers don't support it yet, JSX transform can transpile this syntax is you use supply `harmony` option. With Webpack, this would be [`jsx?harmony` in `loaders`](https://github.com/gaearon/react-dnd/blob/master/examples/webpack.config.js#L19).

Please let me know if this helps!

**Comment by jean-Phil** [comment]
Thank you very much, Dan.   Both answers were most helpful.

**Comment by gaearon** [comment]
Closing since we have examples now.
A much cooler Trello-like example will come with #48.
