### ISSUE TITLE
access state in DropTarget's canDrop(props, monitor)

### ISSUE THREAD

**Issue by carlflor** [gaearon/react-dnd#302]
Is there a way I can access the state of a DropTarget component in canDrop?
I'd like change canDrop based on the state of the component.

For example, I want to dropTarget to reject other dropSource components after it has received one..
from the examples, seems like I can only use the state from the parent component and pass as props to the dragTarget.. is there a simpler way to go about this?

**Comment by gaearon** [comment]
No, this is an intentional decision. Since we're *wrapping* your components we can only react to the different props we receive—not to their internal state changes. You'd need to move the state up. [`SourceBox.js`](https://github.com/gaearon/react-dnd/blob/master/examples/03%20Nesting/Drag%20Sources/SourceBox.js) from examples should give you an idea.

**Comment by carlflor** [comment]
alright! such great help! thanks :)
