### ISSUE TITLE
TypeError: node.setAttribute is not a function in HTML5Backend.js

### ISSUE THREAD

**Issue by ajoseerazo** [gaearon/react-dnd#311]
Hi, I'm getting this error
Uncaught TypeError: node.setAttribute is not a function at HTML5Backend.js:130

My class definition is:
```javascript
var PropTypes = React.PropTypes;

/**
 * Implements the drag source contract.
 */
const itemSource = {
  beginDrag: function (props) {
    return {
      text: props.text
    };
  }
}

ItemTypes = {
  ITEMBOX: 'itembox'
}
/**
 * Specifies the props to inject into your component.
 */
function collect(connect, monitor) {
  return {
    connectDragSource: connect.dragSource(),
    isDragging: monitor.isDragging()
  };
}

@DragSource(ItemTypes.ITEMBOX, itemSource, (connect, monitor) => ({
  connectDragSource: connect.dragSource(),
  isDragging: monitor.isDragging()
}))
class Itembox{
  static propTypes = {
    text: PropTypes.string.isRequired,

    // Injected by React DnD:
    isDragging: PropTypes.bool.isRequired,
    connectDragSource: PropTypes.func.isRequired
  }

  render() {
    const isDragging = this.props.isDragging;
    const connectDragSource = this.props.connectDragSource;
    const text = this.props.text;

    return connectDragSource(
      <div style={{ opacity: isDragging ? 0.5 : 1 }}>
        {text}
      </div>
    );
  }
}

this.Itembox = Itembox
```

I dont know what is the issue. Can you help me? thanks

**Comment by gaearon** [comment]
Please provide a full runnable example.
This doesn't happen in examples, so it should be something unusual with your particular project.

**Comment by gaearon** [comment]
>I dont know what is the issue.

Have you tried looking into it? This is regular JavaScript code, so you can apply the same techniques you usually apply to your applications.

If the error is that `node` doesn't have `setAttribute`, you can inspect what `node` *is* in the debugger. Is it even a node? Is it some special kind of node without `setAttribute` defined? Why? Is it something else than a node? Then what is it? Where was that object passed from?

Doing a basic research will both help you better understand how React DnD works, and get better at debugging applications, and help us come up with a fix sooner.

**Comment by zlanich** [comment]
I am having the same issue that ajoseerazo was having, but before I go off and find a way to get you a working example (which will be a huge pita if not necessary lol), here's what I have going on:

I'm building a Wordpress Page Builder and currently implementing the ability to drag a simple representation of a widget onto the page from a toolbar: [Screenshot of UI](http://drop.zachlanich.com/pzlQ)

I have a ComponentChooseBar React class like so: [ComponentChooseBar.js](http://drop.zachlanich.com/18bZI) - This is the tabbed interface you see in the above UI Screenshot.

I have a ComponentChooseBarOption React class like so: [ComponentChooseBarOption.js](http://drop.zachlanich.com/1dLll) - This is basically just a box with text in it representing the type of component I'm trying to drag.

I'm getting the error node.setAttribute is not a function in HTML5Backend.js and upon dumping "node", it says it's a React Component Wrapper. This seems correct to me, but either way, it's erroring out and it seems like I'm doing everything like in the examples.

Can you provide some help/feedback with the above info? I "can" package this up for a demo, but you would have to pop up a local MySQL and dump my DB in because it's a WP plugin as is. Thanks in advance. I'm dying on this right now as I've spent hours just trying to get DnD to work.

**Comment by gaearon** [comment]
>I'm getting the error node.setAttribute is not a function in HTML5Backend.js and upon dumping "node", it says it's a React Component Wrapper. This seems correct to me

This isn't correct. A node should be a DOM node.

What I think is happening is that [`React.isValidElement()` returns false for your React element here](https://github.com/gaearon/react-dnd/blob/master/src/bindConnectorMethod.js#L26).

My best guess is that React DnD “sees” React 0.14 which is its peer dependency, but somewhere in your application there is React 0.13 bundled. (See the [“duplicate React” problem](https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375).)

The 0.14 React doesn’t “recognize” elements created by 0.13, and this is why the check fails. The solution is to make sure you only have one React in your project, and that it is React 0.14.

**Comment by gaearon** [comment]
For example, you seem to have two different `node_modules` directories:

```js
var React = require('react');
var DragSource = require('../../node_modules/react-dnd/lib/index.js').DragSource;
```

Is that a parent and child project?
I'd say it's likely you have `react` in both, and that's the source of the problem.

**Comment by zlanich** [comment]
Well, turns out, that was only part of the problem :P. My file structure 
was a mess because when I first started the project, I couldn't get 
browserify working for the life of me using online tutorials, so I ended 
up using a boilerplate and half my files were still elsewhere. I updated 
everything and found the duplicate react culprit (react-draggable not 
updating to 0.8.5). Thanks for your help! Hugely appreciated.

Dan Abramov wrote:
