### ISSUE TITLE
@DropTarget takes over my component state?

### ISSUE THREAD

**Issue by SkateFreak** [gaearon/react-dnd#349]
in short:
i have a flex grid, i have a timeout on each flex-item to calculate its BoundingClientRect.
in the container component i set the timeout a little longer then try to access the children's state.

    @DropTarget('FlexItem', dropTarget, (connect, monitor) => ({
        connectDropTarget: connect.dropTarget(),
        isOver: monitor.isOver()
    }))

in componentDidMount i have:

    this.setState({
        isLoading: false,
        rect: ReactDOM.findDOMNode(this).getBoundingClientRect()
    });

when i try to access it's state from the parent component with

    this.props.refs.flexItem.state

i get this:

    Object {
        connectDropTarget: ref()
        isOver: false
    }

i tried removing @DropTarget and i got the result i wanted.
i thought @DropTarget is injecting props, why is the state messed with?
please help me shed some light on this, i have no idea how to approach this.

thanks guys

**Comment by gaearon** [comment]
DropTarget wraps your component into another component.
Technically you can access it like this: `this.props.refs.flexItem.decoratedComponentInstance.state`.

However this is:

1) An API we don't promise to support.
2) An misuse of React API.

In React, the state is private to the component. Other components, even parents, should never use `ref` to access another component's state. A better workaround would be to pass `onBoundingClientRectChange` as a prop to your drop targets, so that they can call `this.props.onBoundingClientRectChange(id, newRect)`. Then the parent component can update a local field without using `ref`s at all.

**Comment by SkateFreak** [comment]
@gaearon thanks for the lesson Dan. exactly what i needed.
