### ISSUE TITLE
Continue drag when outside of DragDropContext

### ISSUE THREAD

**Issue by marek-sed** [gaearon/react-dnd#356]
Hi

I am integrating react component into angular application, so I don't have any root component to wrap
in DragDropContext.

Is there an option to continue dragging when mouse position is outside of root component?

**Comment by marek-sed** [comment]
I realized this issue is related to backend so closing it here.

**Comment by abobwhite** [comment]
@marek-sed Did you figure out a solution for this issue? I am about to embark on a similar journey using react-dnd in react components that are included via angular templates.

**Comment by marek-sed** [comment]
@abobwhite Yes I did. I was using touch backend, https://github.com/yahoo/react-dnd-touch-backend, because I needed to drag SVG elements and it is using regular mouse events and not HTML5 API. There on the line 222, use just remove the bounding rectangle check, it is quite straight forward. 

`    const matchingTargetIds = Object.keys(this.targetNodes)
            .filter((targetId) => {
                const boundingRect = this.targetNodes[targetId].getBoundingClientRect();
                return clientOffset.x >= boundingRect.left &&
                clientOffset.x <= boundingRect.right &&
                clientOffset.y >= boundingRect.top &&
                clientOffset.y <= boundingRect.bottom;
            });` 

I think you can modify html5 backend in same way, but I did not check that one.

**Comment by abobwhite** [comment]
@marek-sed Thanks for the info! I won't be using the touch backend but I will look into it for the HTML5 backend. 

Did you just wrap each of your react components from your disparate angular areas with ```DragDropContext``` each and it worked? For example, ```DragDropContext(HTML5Backend)(QuestionLibrary)```, ```DragDropContext(HTML5Backend)(QuestionToolbar)```, ```DragDropContext(HTML5Backend)(QuestionTree)``` ? These each are wrapped with ngReact to allow the react components (and subcomponents) to render within angular. I need to drag and drop "questions" (etc.) between these.

**Comment by marek-sed** [comment]
@abobwhite Hi, sry for not responding earlier. I am not using ng-react. Until now I used webpack to bundle it and then just display it in angular app. 

Currentyl I am trying different approach. I have a cutsom directive(RootDirective) that wraps react-dom.render(). I think ng-react is doing same thing. So just wrap root component in ng-react if you want to use it. Each react component is just a function so to create different components inside the root component I use angular factories and inject it into RootDirective. And the function that is returned from factory is wrapped in React-DND stuff.

**Comment by abobwhite** [comment]
@marek-sed Thanks for the tips! Let me see if I'm following you correctly.

You're suggesting that I create a root directive in ngReact for all my angular pieces + react components? If that's the case, I would think that would cause a problem with the angular pieces not rendering or being bound correctly. The point of pulling in react was that I didn't have to change everything, I can just change some pieces and let angular expose them where needed. I could go the route where my entire page is wrapped with a react component and then everything inside is also react, but I don't really want to have to convert all that display and display logic into react if I don't need to.

Here is a simplified example. Here i'm using the ngReact directive and referencing my react component by name (either as an angular factory or an angular value) but I've also used the ngReact method which itself returns a react component wrapped in an angular directive to be used as you would a normal angular directive...but I digress:

```
<div id="myPage" ng-controller="SomeExampleCtrl">
	<!-- angular-owned HTML -->
	<angular-directive-1></angular-directive-1>
	<!-- Other angular-owned HTML -->
	<angular-directive-2></angular-directive-2>
	<!-- Other angular-owned HTML -->
</div>
```
```
<!-- angular-directive-1 -->
<div>
        <!-- React Dnd happens in here -->
	<react-component="reactComponent1"></react-component>
</div>
```
```
<!-- angular-directive-2 -->
<div>
        <!-- React Dnd happens in here too! -->
	<react-component="reactComponent2"></react-component>
</div>
```

**Comment by abobwhite** [comment]
Hey @marek-sed I've looked into this a little more and I'm really hitting a wall. The problem is that everything on the page can't be turned into React. It's a ton of angular code. Inside this page, however, I have several react components now wrapped by ngReact that need to be able to DnD between each other. I understand your concept of a root directive which wraps a react component but that root component cannot contain any angular (only react) for it to work as far as I know. I understand using angular factories for my react components on the page and injecting them into my root directive but it's not clear to me how I would then render these injected components alongside angular all the while inside a react-owned root component which has the ```DragDropContext```.

I appreciate your time and help on this. Thanks.

**Comment by marek-sed** [comment]
I dont think that is possible, once you wrap in ng-react the component is rendered when directive is found on page, so it is game over.

If you cant separate react from angular, like top part of page is angular form and bottom part of page is some component in which you can use ReactDnd, you need to look for angular dnd solutiion.

**Comment by abobwhite** [comment]
@marek-sed Thanks for all the input. I decided to abandon react-dnd last night and am rolling my own from the simple https://github.com/asbjornenge/react-drag-and-drop. I used to use kendo-ui DnD wrapped for angular but since all of my areas that use DnD are now in react, an angular solution is not feasible. I think I will create a new issue here in react-dnd to allow the same DragDropContext to be re-used. Maybe a DragDropContext could have a named key or something.
