### ISSUE TITLE
Can't select input or texarea content

### ISSUE THREAD

**Issue by maxsalven** [gaearon/react-dnd#358]
From #178:

'Attempt to select input or textarea content with touchpad/mouse starts dragging parent element.'

This works in Safari 9.0.2 but does not work in Chrome 47.0

**Comment by gaearon** [comment]
I can’t reproduce this with Chrome 47. I tested OS X and Windows.
Here’s what I see:

![feb 14 2016 00 25](https://cloud.githubusercontent.com/assets/810438/13030903/afd5d7b4-d2b1-11e5-8670-c3f03722cdcb.gif)

Selecting text works fine. Note that *if you drag by the corner where there is no text yet*, indeed the textarea is draggable. This is just how browser works; we can’t prevent it without introducing fragile checks that would break with other edge cases. If you’d like to disable this, your best bet is to keep some kind of `isEditing` state in the parent component, pass `isEditing`, `onFocus` and `onBlur` to your drag source, and define `canDrag(monitor, props)` to return `!props.isEditing` so that you explicitly forbid dragging while the input if focused.

**Comment by maxsalven** [comment]
It seems to work for textarea but not for `input`. I added an `<input type="text" />` to the Sortable/Simple example:

![reactdnd](https://cloud.githubusercontent.com/assets/4144910/13625237/644aaf34-e5f0-11e5-86be-0bf110cd43e1.gif)

**Comment by rbehal** [comment]
This is not documented very well, but if you add the class name `nodrag` this works to not allow dragging by the text input field, meaning you can select and highlight text with your cursor. 

No other solutions solved my issue.

```
      <>
        <Input
          disabled={isDisabled}
          value={value}
          onChange={handleChange}
          className={'nodrag'}
          placeholder={placeholder}
          multiline
          error={error_message}
        />
      </>
```
