### ISSUE TITLE
Wrapping a component in DropTarget hides refs functions

### ISSUE THREAD

**Issue by Eightyplus** [gaearon/react-dnd#378]
I have a DropTarget, which works fine as a droppable target. However, I need to call a method on the compoent from the parent (as by this example: https://facebook.github.io/react/tips/expose-component-functions.html), but the method is not exposed when wrapped in a DropTarget. 

```
 <Droppable id={item.id} ref="droppable" />

class Droppable extends Component {
    getViews = () => {
    ....
```

When I call the parent this.refs.droppable.getViews(), I get the following error:
```
TypeError: this.refs.droppable.getViews is not a function
```
When I remove the 
```
export default DropTarget(ItemTypes.ITEM, dropTarget, collect)(...);
```
and keep
```
export default Droppable;
```
the problem does not occur. I guess it must be the wrapping that causes the problem. Initially I thought it was the binding or ES6/7 error - but using that syntax didn't solve my problem.

**Comment by gaearon** [comment]
`DropTarget` *wraps* your component into another component. So its instance is not the same as your component’s instance.

In general, using `ref` is a bad idea. It encourages tight coupling of components which is against the conceptual model of React. Try to only use top-down data flow and props as component interface.

If you absolutely must reach into the wrapped component, you can use `this.refs.droppable. getDecoratedComponentInstance().getViews()` instead of `this.refs.droppable.getViews()`. Hope this helps!

**Comment by Eightyplus** [comment]
Thanks for the fast reply, it works! Eventhough the class is wrapped it appeared the same without the ref methods. I have also read ref is a bad idea, but I have to export props along with view properties (getBoundingClientRect()).
Due to the event mechanish of react-dnd I can't seem to get the final rendered component. I expected it to be available in endDrag, but here no functions are available (maybe I should use getDecoratedComponentInstance() ?) . To avoid complexity I turned to refs.

Will see if I can refactor it when I get the hang of React. Rewriting my drag/drop/sortable jQuery webpage, and react-dnd is really a nice package. Thanks!
