### ISSUE TITLE
2.1.0 Uncaught TypeError: process.nextTick is not a function

### ISSUE THREAD

**Issue by TeemoWan** [gaearon/react-dnd#380]
"react-dnd": "^2.0.2" and "react-dnd-html5-backend": "^2.0.2" is normal, but update to 
 "react-dnd": "^2.1.0" and "react-dnd-html5-backend": "^2.1.2".

Exception from Tracker recompute function:
debug.js:41 TypeError: process.nextTick is not a function
    at requestFlush (raw.js:95)
    at rawAsap (raw.js:18)
    at Object.asap [as default] (asap.js:26)
    at HandlerRegistry.removeSource (HandlerRegistry.js:167)
    at unregisterSource (registerSource.js:11)
    at Disposable.dispose (Disposable.js:24)
    at CompositeDisposable.dispose (CompositeDisposable.js:93)
    at SerialDisposable.dispose (SerialDisposable.js:73)
    at DragDropContainer.componentWillUnmount (decorateHandler.js:119)
    at ReactCompositeComponentMixin.unmountComponent (ReactCompositeComponent.js:243)

raw.js:95 Uncaught TypeError: process.nextTick is not a function

**Comment by gaearon** [comment]
What bundler do you use? It seems that your bundler doesn’t respect the [`browser` field](https://github.com/kriskowal/asap/blob/d7359b771fb3ff41f8bfcbb1fa00ade7126fc622/package.json#L19) of `package.json` in the `asap` package.

If you use Webpack, this should not happen by default. If you use Webpack and it happens, make sure you don’t override [`resolve.packageAlias`](https://webpack.github.io/docs/configuration.html#resolve-packagealias), or, if you override it for some reason, that it includes `'browser'` as one of its values.

If you use Browserify, this also should not happen by default. If you use Browserify and it happens, make sure you are **not** running it with a `--no-bf` (aka `--no-browser-field`) field. 

If you use something else, please refer to your bundler’s documentation on how to enable resolution of [`browser` field in `package.json`](https://github.com/defunctzombie/package-browser-field-spec).

If your bundler does not support this, you can switch to using a UMD build in `react-dnd/dist/react-dnd.min.js`. Most bundlers let you specify aliases for individual packages. The UMD build does not contain references to `process`.

If your bundler does not allow you to specify aliases, please import from `react-dnd/dist/react-dnd.min.js` directly. Unfortunately there is no better solution in this case.

I would also advise you to switch to a popular bundler like Webpack or Browserify that handles such cases correctly. We don’t plan to fix it in React DnD because we don’t consider this a bug. Popular bundlers already support this.

**Comment by TeemoWan** [comment]
Thank you!I use meteor and react together.

**Comment by gaearon** [comment]
From https://github.com/meteor/meteor/blob/release-1.3/packages/modules/README.md:

>Note: in the beta release of Meteor 1.3, Node modules are imported using the same entry point on both the client and the server (either the module identified by the main field of the package.json file, or index.js). For this reason, you should only import npm libraries on the client if you are sure they will work in a browser environment. **We are considering implementing support for the browser field in package.json files, but we didn’t want to delay the beta release just for that.**

**Comment by gaearon** [comment]
Relevant issues: 

https://github.com/meteor/meteor/issues/6056
https://github.com/meteor/meteor/issues/6167
https://github.com/meteor/meteor/issues/6198
