### ISSUE TITLE
holding ctrl while drag/dropping

### ISSUE THREAD

**Issue by soccertwin03** [gaearon/react-dnd#394]
Is there a mechanism to determine if a certain key is being pressed on drop?  This would be used for something similar to windows explorer. (drag/drop to move, drag/drop/ctrl to copy).

**Comment by gaearon** [comment]
This is not currently supported by https://github.com/gaearon/react-dnd-html5-backend although I could imagine this would be possible with a custom backend. It might be possible to add there but I haven’t given it much thought. If you decide to look at it there, [`dropEffect`](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/dropEffect) would be related.

From what I remember, right now we completely disregard the keys and instead let you specify the drop effect as an option to `connectDragSource` as [demostrated here](https://github.com/gaearon/react-dnd/blob/ca227203f0e3896789fbc29141b75d91701c0c7d/examples/05%20Customize/Drop%20Effects/SourceBox.js#L40). You might actually achieve what you want by using `setState({ dropEffect })` on key down and key up, and using `this.state.dropEffect` in your `connectDragSource` call.

I’m closing because I don’t plan to work on this, but hopefully these are enough pointers to get started.

**Comment by gaearon** [comment]
According to https://github.com/gaearon/react-dnd-html5-backend/issues/23, the browser won’t trigger keydown and keyup during dragging so my earlier suggestion wouldn’t work.

I suggest you to track https://github.com/gaearon/react-dnd-html5-backend/issues/23. I don’t have plans to implement this but somebody else might.

**Comment by hpurmann** [comment]
@soccertwin03 Maybe our proposal could help you: https://github.com/gaearon/react-dnd-html5-backend/issues/58
