### ISSUE TITLE
Attribute draggable not set to true on first iteration of a map

### ISSUE THREAD

**Issue by 6ewis** [gaearon/react-dnd#410]
```
let uniqEntityTypes = Array.from(getUniqueEntityTypes()).map((entityType, index) => {
      return connectDragSource(
               <div style={{opacity}} key={index}>
                 <i className={classEntityTypes[entityType]}>
                 </i>
                 <div style={styleIconLabel}> 
                   { entityType } 
                  </div>
               </div>
             );
   });
```
**draggable is set to true only on the second iteration, the first iteration does not have draggable set to true**. _I'll extract the content of div into its own component later (edit: note that i extracted the component and it's working now):_
Iteration 1:
```
<div style="opacity: 1;" data-reactid=".0.0.0.0.0.1.0.0.0.1:$0"><i class="fa fa-user fa-3x" data-reactid=".0.0.0.0.0.1.0.0.0.1:$0.0"></i><div data-reactid=".0.0.0.0.0.1.0.0.0.1:$0.1">Individual</div></div>

```
Iteration 2:
```
<div style="opacity: 1;" data-reactid=".0.0.0.0.0.1.0.0.0.1:$1" draggable="true"><i class="fa fa-building-o fa-3x" data-reactid=".0.0.0.0.0.1.0.0.0.1:$1.0"></i><div data-reactid=".0.0.0.0.0.1.0.0.0.1:$1.1">Company</div></div>
```

**Browser: Chrome
react-dnd: 2.1.3**

**Comment by 6ewis** [comment]
note that i extracted the component and made it more modular and it's working now. Nevertheless, I'm curious to know why it's not working inside of the map()

**Comment by billyjanitsch** [comment]
Hi @6ewis! If you have time, could you try to come up with a more minimal reproducible example (i.e. without undefined variables like `connectDragSource`)? It's hard for me to look into this without more context.

As far as I can tell, depending on where `connectDragSource` is coming from, this is expected behavior. `connectDragSource` is typically generated by a per-component call to `connect.dragSource`, so I wouldn't expect a single instance of it to work across multiple components in a map.

Feel free to reopen the issue if you think this is actually a bug.

**Comment by 6ewis** [comment]
@billyjanitsch It is a bug. Note that extracting the same exact piece of code in its own component, and importing it in the file that does the map() work. I'll write a minimal reproducible example when I have a minute.

**Comment by neeco90** [comment]
sorry guys, I have the same issue, so there is no solution to this?? I'm asking cause I see the issue closed, and I need to know cause I'm trying to implement it on a work project. Thnks
