### ISSUE TITLE
0px height on chessboard tutorial

### ISSUE THREAD

**Issue by ffxsam** [gaearon/react-dnd#422]
I'm just copying the code into my project as I'm just looking for a starting point before getting into react-dnd specific stuff. Unfortunately, the board is collapsed to 0px. Is there a mistake in the example code? I had to use `height: 100vh` to fix it:

```javascript
// Board.js

// ...
    return (
      <div className="Board" style={{
        width: '100%',
        height: '100vh',
        display: 'flex',
        flexWrap: 'wrap'
      }}>
// ...
```

**Comment by billyjanitsch** [comment]
This is not a mistake, you just need to make sure to render the board in a DOM node that [has an explicit height](https://github.com/gaearon/react-dnd/blob/master/examples/00%20Chessboard/Tutorial%20App/index.js#L40), or else it will default to 0.

**Comment by ffxsam** [comment]
But if one follows the tutorial exactly (which I did), the tutorial's result doesn't match mine. That's what I'm pointing out.

**Comment by billyjanitsch** [comment]
`<Board>` fills its container by design. In the tutorial, it's being rendered into a div with id "root". That div is left up to you; if it has height 0 then `<Board>` will as well.

I agree that it wouldn't hurt to be more explicit about this. If you want to submit a PR for the [Tutorial docs page](https://github.com/gaearon/react-dnd/blob/master/docs/00%20Quick%20Start/Tutorial.md), I'll merge it. :)
