### ISSUE TITLE
delegate shouldComponentUpdate to wrapped component

### ISSUE THREAD

**Issue by HermanBovens** [gaearon/react-dnd#499]
I noticed that _React Developer Tools_, with the _Trace React Updates_ option enabled, shows the components that are wrapped in DragSource or DropTarget as being updated, even when debugging proves that the wrapped components return false from `shouldComponentUpdate()` and they are not being rerendered.

I guess the wrappers could delegate `shouldComponentUpdate()` to the wrapped components so that they themselves won't be updated if the wrapped components don't need to be.  The performance gain may be small (although in my case I have a large table where the cells are both drag sources and drop targets) but at least this would make it easier to see in _React Developer Tools_ which components are really updating.

**Comment by kesne** [comment]
I think that the wrapped component should be able to write it's own `shouldComponentUpdate` (or extends from `React.PureComponent`). This doesn't seem like something `react-dnd` should have an opinion on.

**Comment by HermanBovens** [comment]
I think you misunderstood me.  Of course the wrapped component can have it's own shouldComponentUpdate(), but the react-dnd wrapper always returns true even if the wrapped component returns false.  Apart from a small performance penalty (which may be significant enough in my case where I have thousands of table cells wrapped), it makes it impossible to see in React Developer Tools whether or not the wrapped components are being updated.

**Comment by kesne** [comment]
Ah sorry! I don't think I've seen that pattern before, have you seen other HOCs that do what you're describing? If so I'd be happy to take a PR that implemented it.

**Comment by HermanBovens** [comment]
I'm fairly new to React and this is the first HOC I'm using, so I haven't seen this before.  I'm not sure it would apply to all HOCs.

**Comment by kesne** [comment]
After thinking about this more, we'd have to hoist up the `shouldComponentUpdate` call from the wrapped component, which I think is more trouble than it's worth (especially around the edge cases like what if it's defined different on the prototype than on the instance, what if it relies on dnd props, etc)..

**Comment by walnutzhang** [comment]
I know this issue was closed but I've encountered this problem recently, so I wanna share my solution to this problem.

I was working on a file list component which renders a bunch of file blocks. each block is a DragSource and a DropTarget at the same time. So I use DragSource and RragTarget HOC to wrap the block component.

when the list is short, like there're  50 or something. it's ok to drag around and sort this file list. but it scales to hundreds like 500 or above, the drag and drop will suffer painfully.

I use react-addons-perf and Chrome dev tools to profile the whole drag and sort process, and it shows that everytime I drag a block, all other blocks in the list rerendered. But, it's not the original block component I wrote that rerendered(I use shouldComponentUpdate to make sure it will rerender as expect), it's the wrapped instance rerendered. and every wrapped component wrapped by DragSource and DropTarget HOC takes 30-50ms to rerender itself, without the original block component rerendering. that's ridiculous!  

for now, according to what @kesne said, I can't modify or 'delegate' DragSource's and DragTarget's shouldComponentUpdate methods. **The only way I can solve this problem is to use another HOC to wrap the wrapped aka DnDed component, and inside the new HOC, I use shouldComponentUpdate to make sure the wrapped component will rerender only I want it to.**

although it's not a perfect solution I think....

hope it helps.
