### ISSUE TITLE
hovering trouble

### ISSUE THREAD

**Issue by deser** [gaearon/react-dnd#75]
https://monosnap.com/image/G54T5ogrqiSHPjB1P4mcwaJ8UauFlS
Hello! I think that I found trouble in this.getDropState(TYPE).isHovering. As you can see on the screenshot above when there is some drop targets in hierarchy  they are ALL has isHovering state.
But I think that hovering state shouldn't bubble from child to parent (on screenshot red arrows show where hovering is wrong).

Thank you!

**Comment by nelix** [comment]
You could try adding event.stopPropagation() to the over dropTarget event, we can consider this as default behaviour for version 1.0

**Comment by nelix** [comment]
```javascript
dropTarget: {
  over(component, item, e) {
    e.stopPropagation();
  }
}
```
I have not had time to try my self however

**Comment by deser** [comment]
OK, I'll try thanks a lot!

**Comment by gaearon** [comment]
I don't think this will work. Drop state is determined by drop target type and enter/leave events.

Either way, **it's not recommended to call `stopPropagation` yourself**. We will probably remove `e` in future altogether because that exposes internal implementation and encourages dirty workarounds. 

There are both cases when you want this nesting behavior and cases when you don't. Currently you can implement `canDrop` on parent components and return `false` if you know there's an active child handling them already. This will require manually telling parent that child is active from child's `enter` and `leave` events.

A better way would be to mirror what we do with `acceptDrop`. It receives `isHandled` which tells whether there is a child that already handled drop. Perhaps we should have a similar parameter for `canDrop`: `canDrop(component, item, isHandled)`. Parent components can then decide whether they want to activate if they know some child is already active.

**Comment by deser** [comment]
ishandled inside candrop on my mind is the best solution

**Comment by gaearon** [comment]
If you'd like to make a PR, go for it! We're a bit busy with large-scale refactoring so it's going to take some time to add this.

**Comment by gaearon** [comment]
This issue is superseded by #87. I'll close it, please let's continue the discussion there!
